CREATE OR REPLACE PROCEDURE CREATE_NEW_USER(
    U_HANDLE IN CONTESTANT.HANDLE%TYPE,
    U_EMAIL IN USER_ACCOUNT.EMAIL%TYPE,
    U_PASS IN USER_ACCOUNT.PASSWORD%TYPE,
    U_DOB IN USER_ACCOUNT.DATE_OF_BIRTH%TYPE,
    U_ID OUT CONTESTANT.ID%TYPE
) IS
    U_RANK RANK.ID%TYPE;
BEGIN
    U_ID := CNTSTNT_SEQ.NEXTVAL;
    INSERT INTO
        CONTESTANT(ID, HANDLE, TYPE)
    VALUES
        (U_ID, U_HANDLE, 'USER');
    
    SELECT 
        ID
    INTO
        U_RANK
    FROM
        RANK
    WHERE
        0 BETWEEN MIN_RATING AND MAX_RATING;

    INSERT INTO
        USER_ACCOUNT(ID, EMAIL, PASSWORD, RANK_ID, DATE_OF_BIRTH)
    VALUES
        (U_ID, U_EMAIL, U_PASS, U_RANK, U_DOB);
END;
