
DROP TABLE CONTEST;
DROP TABLE MESSAGE;
DROP TABLE USER_ACCOUNT;
DROP TABLE TEAM;
DROP TABLE CONTESTANT;
DROP TABLE RANK;
DROP TABLE TAG;
DROP TABLE LANGUAGE;
DROP TABLE CITY;
DROP TABLE COUNTRY;
DROP TABLE ORGANIZATION;