CREATE TABLE ORGANIZATION (
    ID NUMBER,
    NAME VARCHAR2(100) NOT NULL,

    CONSTRAINT ORG_PK PRIMARY KEY(ID),
    CONSTRAINT ORG_NAME_U UNIQUE(NAME)
);
CREATE TABLE COUNTRY (
    ID NUMBER,
    NAME VARCHAR2(50) NOT NULL,

    CONSTRAINT CNTRY_PK PRIMARY KEY(ID),
    CONSTRAINT CNTRY_NAME_U UNIQUE(NAME)
);
CREATE TABLE CITY (
    ID NUMBER,
    COUNTRY_ID NUMBER,
    NAME VARCHAR2(50) NOT NULL,

    CONSTRAINT CITY_PK PRIMARY KEY(ID, COUNTRY_ID),
    CONSTRAINT CITY_NAME_U UNIQUE(NAME)
);
CREATE TABLE LANGUAGE (
    ID NUMBER,
    NAME VARCHAR2(50) NOT NULL,
    COMMAND VARCHAR2(100) NOT NULL,

    CONSTRAINT LANG_PK PRIMARY KEY (ID),
    CONSTRAINT LANG_NAME_U UNIQUE(NAME)
);
CREATE TABLE TAG (
    ID NUMBER,
    NAME VARCHAR2(50) NOT NULL,
    TYPE VARCHAR2(20),

    CONSTRAINT TAG_PK PRIMARY KEY (ID),
    CONSTRAINT TAG_NAME_U UNIQUE(NAME),
    CONSTRAINT TAG_TYPE_CHK CHECK(TYPE IN ('BLOG', 'PROBLEM'))
);
CREATE TABLE RANK (
    ID NUMBER,
    NAME VARCHAR2(50) NOT NULL,
    COLOR VARCHAR2(50) NOT NULL,
    MIN_RATING NUMBER NOT NULL,
    MAX_RATING NUMBER NOT NULL,
    DIVISION NUMBER NOT NULL,

    CONSTRAINT RANK_PK PRIMARY KEY (ID),
    CONSTRAINT RANK_NAME_U UNIQUE(NAME),
    CONSTRAINT RANK_RATING_CHK CHECK(MIN_RATING <= MAX_RATING)
);
CREATE TABLE CONTESTANT (
    ID NUMBER,
    TYPE VARCHAR2(20),
    HANDLE VARCHAR2(100) NOT NULL,
    CREATION_TIME DATE DEFAULT(SYSDATE) NOT NULL,

    CONSTRAINT CNTSTNT_PK PRIMARY KEY(ID),
    CONSTRAINT CNTSTNT_TYPE_CHK CHECK(TYPE IN ('TEAM', 'USER')),
    CONSTRAINT CNTSTNT_HANDLE_U UNIQUE(HANDLE)
);
CREATE TABLE TEAM (
    ID NUMBER,
    DESCRIPTION VARCHAR2(500),

    CONSTRAINT TEAM_PK PRIMARY KEY(ID),
    CONSTRAINT TEAM_CNTSTNT_FK FOREIGN KEY(ID) REFERENCES CONTESTANT(ID)
);
-- DONE
CREATE TABLE USER_ACCOUNT (
    ID NUMBER,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    PASSWORD VARCHAR2(200),
    EMAIL VARCHAR2(200),
    RATING NUMBER,
    RANK_ID NUMBER,
    LOGIN_TIME DATE,
    PICTURE VARCHAR2(200),
    DATE_OF_BIRTH DATE,
    ORG_ID NUMBER,
    COUNTRY_ID NUMBER,
    CITY_ID NUMBER
);
CREATE TABLE MESSAGE (
    ID NUMBER,
    BODY VARCHAR2(500),
    TIME_SENT DATE,
    TIME_READ DATE,
    FROM_USER_ID NUMBER,
    TO_USER_ID NUMBER
);
CREATE TABLE CONTEST (
    ID NUMBER,
    NAME VARCHAR2(50),
    TIME_START DATE,
    DURATION NUMBER,
    MIN_RATED NUMBER,
    MAX_RATED NUMBER
);
CREATE TABLE BLOG_POST (
    ID NUMBER,
    TITLE VARCHAR2(50),
    BODY VARCHAR2(1000),
    CREATION_TIME DATE,
    CONTEST_ID NUMBER,
    AUTHOR_ID NUMBER
);
CREATE TABLE POST_COMMENT (
    ID NUMBER,
    BODY VARCHAR2(500),
    CREATION_TIME DATE,
    AUTHOR_ID NUMBER,
    BLOG_ID NUMBER,
    PARENT_ID NUMBER
);
CREATE TABLE PROBLEM (
    ID NUMBER,
    NAME VARCHAR2(20),
    CONTEST_ID NUMBER,
    BODY VARCHAR2(1000),
    SOURCE_LIMIT NUMBER,
    TIME_LIMIT NUMBER,
    MEMORY_LIMIT NUMBER,
    RATING NUMBER
);
CREATE TABLE TEST_FILE (
    ID NUMBER,
    PROBLEM_ID NUMBER,
    TEST_NUMBER NUMBER,
    TYPE VARCHAR2(20),
    INPUT_URL VARCHAR2(100),
    OUTPUT_URL VARCHAR2(100)
);
CREATE TABLE SUBMISSION (
    ID NUMBER,
    PROBLEM_ID NUMBER,
    AUTHOR_ID NUMBER,
    SUBMISSION_TIME DATE,
    JUDGE_TIME DATE,
    LANG_ID DATE,
    CODE_SIZE NUMBER
);
CREATE TABLE USER_USER_FOLLOW (
    FOLLOWER_ID NUMBER,
    FOLLOWED_ID NUMBER
);
CREATE TABLE USER_TEAM_MEMBER (
    USER_ID NUMBER,
    TEAM_ID NUMBER,
    TYPE VARCHAR2(20)
);
CREATE TABLE BLOG_USER_VOTE (
    USER_ID NUMBER,
    BLOG_ID NUMBER,
    TYPE VARCHAR2(20)
);
CREATE TABLE USER_CONTEST_ADMIN (
    USER_ID NUMBER,
    CONEST_ID NUMBER,
    TYPE VARCHAR2(20)
);
CREATE TABLE CONTEST_REGISTRATION (
    CONTESTANT_ID NUMBER,
    CONTEST_ID NUMBER,
    STANDING NUMBER,
    RATING_CHANGE NUMBER
);
CREATE TABLE COMMENT_USER_VOTE (
    USER_ID NUMBER,
    COMMENT_ID NUMBER,
    TYPE VARCHAR2(20)
);
CREATE TABLE BLOG_TAG (
    BLOG_ID NUMBER,
    TAG_ID NUMBER
);
CREATE TABLE CONTEST_ANNOUNCEMENTS (
    ID NUMBER,
    CONTEST_ID NUMBER,
    BODY VARCHAR2(500),
    CREATION_TIME DATE
);
CREATE TABLE PROBLEM_TAG (
    PROBLEM_ID NUMBER,
    TAG_ID NUMBER
);
CREATE TABLE SUBMISSION_TEST_RUN (
    SUBMISSION_ID NUMBER,
    TEST_ID NUMBER,
    RESULT VARCHAR2(20),
    RUNTIME NUMBER, 
    MEMORY NUMBER
);