CREATE TABLE ORGANIZATION (
    ID NUMBER,
    NAME VARCHAR2(100)
);
CREATE TABLE COUNTRY (
    ID NUMBER,
    NAME VARCHAR2(50)
);
CREATE TABLE CITY (
    ID NUMBER,
    NAME VARCHAR2(50),
    COUNTRY_ID NUMBER
);
CREATE TABLE LANGUAGE (
    ID NUMBER,
    NAME VARCHAR2(50),
    COMMAND VARCHAR2(100)
);
CREATE TABLE TAG (
    ID NUMBER,
    NAME VARCHAR2(50),
    TYPE VARCHAR2(20)
);
CREATE TABLE RANK (
    ID NUMBER,
    NAME VARCHAR2(50),
    COLOR VARCHAR2(50),
    MIN_RATING NUMBER,
    MAX_RATING NUMBER,
    DIVISION NUMBER
);
CREATE TABLE CONTESTANT (
    ID NUMBER,
    TYPE VARCHAR2(20),
    HANDLE VARCHAR2(100),
    CREATION_TIME DATE
);
CREATE TABLE TEAM (
    ID NUMBER,
    DESCRIPTION VARCHAR2(500)
);
CREATE TABLE USER_ACCOUNT (
    ID NUMBER,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    PASSWORD VARCHAR2(200),
    EMAIL VARCHAR2(200),
    RATING NUMBER,
    RANK_ID NUMBER,
    LOGIN_TIME DATE,
    PICTURE VARCHAR2(200),
    DATE_OF_BIRTH DATE,
    ORG_ID NUMBER,
    COUNTRY_ID NUMBER,
    CITY_ID NUMBER
);
CREATE TABLE MESSAGE (
    ID NUMBER,
    BODY VARCHAR2(500),
    TIME_SENT DATE,
    TIME_READ DATE,
    FROM_USER_ID NUMBER,
    TO_USER_ID NUMBER
);
CREATE TABLE CONTEST (
    ID NUMBER,
    NAME VARCHAR2(50),
    TIME_START DATE,
    DURATION NUMBER,
    MIN_RATED NUMBER,
    MAX_RATED NUMBER
)