CREATE SEQUENCE ORG_SEQ 
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE CNTRY_SEQ 
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE CITY_SEQ 
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE LANG_SEQ 
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE TAG_SEQ 
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE RANK_SEQ 
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE CNTSTNT_SEQ 
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE MSG_SEQ 
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE CITY_SEQ 
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE CNTST_SEQ 
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE BLOG_SEQ 
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE CMMNT_SEQ 
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE PRBLM_SEQ 
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE TEST_SEQ 
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SBMSSN_SEQ 
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE ANNCMNT_SEQ 
START WITH 1
INCREMENT BY 1;